//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NileHotels.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("NileHotels.Resources.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Actual CheckOut Time.
        /// </summary>
        public static string ActualCheckOut {
            get {
                return ResourceManager.GetString("ActualCheckOut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Contact.
        /// </summary>
        public static string Add_Contact {
            get {
                return ResourceManager.GetString("Add Contact", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add New.
        /// </summary>
        public static string Add_New {
            get {
                return ResourceManager.GetString("Add New", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Contact.
        /// </summary>
        public static string Addcontact {
            get {
                return ResourceManager.GetString("Addcontact", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Arabic Address.
        /// </summary>
        public static string AddressAr {
            get {
                return ResourceManager.GetString("AddressAr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Amount Paid.
        /// </summary>
        public static string Amount {
            get {
                return ResourceManager.GetString("Amount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Asset.
        /// </summary>
        public static string Asset {
            get {
                return ResourceManager.GetString("Asset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Asset Status.
        /// </summary>
        public static string Asset_Status {
            get {
                return ResourceManager.GetString("Asset Status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Asset Type.
        /// </summary>
        public static string Asset_Type {
            get {
                return ResourceManager.GetString("Asset Type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Available Rooms.
        /// </summary>
        public static string Available_Rooms {
            get {
                return ResourceManager.GetString("Available Rooms", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BirthDate.
        /// </summary>
        public static string BirthDate {
            get {
                return ResourceManager.GetString("BirthDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Building Number.
        /// </summary>
        public static string BuildingNo {
            get {
                return ResourceManager.GetString("BuildingNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date of Entry.
        /// </summary>
        public static string CheckInTime {
            get {
                return ResourceManager.GetString("CheckInTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date of Exit.
        /// </summary>
        public static string CheckOut {
            get {
                return ResourceManager.GetString("CheckOut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose a naturel of Asset.
        /// </summary>
        public static string Choose_a_naturel_of_Asset {
            get {
                return ResourceManager.GetString("Choose a naturel of Asset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cities.
        /// </summary>
        public static string cities {
            get {
                return ResourceManager.GetString("cities", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to City.
        /// </summary>
        public static string City {
            get {
                return ResourceManager.GetString("City", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Client.
        /// </summary>
        public static string Client {
            get {
                return ResourceManager.GetString("Client", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Client Contact.
        /// </summary>
        public static string Client_Contact {
            get {
                return ResourceManager.GetString("Client Contact", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Client info.
        /// </summary>
        public static string Client_info {
            get {
                return ResourceManager.GetString("Client info", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clients.
        /// </summary>
        public static string Clients {
            get {
                return ResourceManager.GetString("Clients", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clients Report.
        /// </summary>
        public static string Clients_Report {
            get {
                return ResourceManager.GetString("Clients Report", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close.
        /// </summary>
        public static string Close {
            get {
                return ResourceManager.GetString("Close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Company.
        /// </summary>
        public static string Company {
            get {
                return ResourceManager.GetString("Company", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact Type.
        /// </summary>
        public static string Contact_Type {
            get {
                return ResourceManager.GetString("Contact Type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contacts.
        /// </summary>
        public static string Contacts {
            get {
                return ResourceManager.GetString("Contacts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact Type.
        /// </summary>
        public static string ContactType {
            get {
                return ResourceManager.GetString("ContactType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contract.
        /// </summary>
        public static string Contract {
            get {
                return ResourceManager.GetString("Contract", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  Amont.
        /// </summary>
        public static string contract_Amont {
            get {
                return ResourceManager.GetString("contract Amont", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contract&apos;s Income.
        /// </summary>
        public static string contract_s_income {
            get {
                return ResourceManager.GetString("contract\'s income", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contract Taxes.
        /// </summary>
        public static string Contract_Taxes {
            get {
                return ResourceManager.GetString("Contract Taxes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contract Number.
        /// </summary>
        public static string ContractNo {
            get {
                return ResourceManager.GetString("ContractNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contract Only ?.
        /// </summary>
        public static string ContractOnly {
            get {
                return ResourceManager.GetString("ContractOnly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contracts.
        /// </summary>
        public static string Contracts {
            get {
                return ResourceManager.GetString("Contracts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CountofPerson.
        /// </summary>
        public static string CountofPerson {
            get {
                return ResourceManager.GetString("CountofPerson", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Countries.
        /// </summary>
        public static string countries {
            get {
                return ResourceManager.GetString("countries", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Country.
        /// </summary>
        public static string Country {
            get {
                return ResourceManager.GetString("Country", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Country.
        /// </summary>
        public static string CountryId {
            get {
                return ResourceManager.GetString("CountryId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CR.
        /// </summary>
        public static string CR {
            get {
                return ResourceManager.GetString("CR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Currencies.
        /// </summary>
        public static string Currencies {
            get {
                return ResourceManager.GetString("Currencies", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current quantity.
        /// </summary>
        public static string CurrentQty {
            get {
                return ResourceManager.GetString("CurrentQty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Daily Contracts.
        /// </summary>
        public static string Daily_Contracts {
            get {
                return ResourceManager.GetString("Daily Contracts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date.
        /// </summary>
        public static string Date {
            get {
                return ResourceManager.GetString("Date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description/Note.
        /// </summary>
        public static string Decription {
            get {
                return ResourceManager.GetString("Decription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        public static string Delete {
            get {
                return ResourceManager.GetString("Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        public static string Description {
            get {
                return ResourceManager.GetString("Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Double Bed Number.
        /// </summary>
        public static string DoubleBedNo {
            get {
                return ResourceManager.GetString("DoubleBedNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rent Period.
        /// </summary>
        public static string Duration {
            get {
                return ResourceManager.GetString("Duration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        public static string Edit {
            get {
                return ResourceManager.GetString("Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        public static string Email {
            get {
                return ResourceManager.GetString("Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Employee handover data.
        /// </summary>
        public static string Employee_handover_data {
            get {
                return ResourceManager.GetString("Employee handover data", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Employee Name.
        /// </summary>
        public static string Employee_Name {
            get {
                return ResourceManager.GetString("Employee Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Employees.
        /// </summary>
        public static string Employees {
            get {
                return ResourceManager.GetString("Employees", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Employees Report.
        /// </summary>
        public static string Employees_Report {
            get {
                return ResourceManager.GetString("Employees Report", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EndDate.
        /// </summary>
        public static string EndDate {
            get {
                return ResourceManager.GetString("EndDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter your email and password to sign in.
        /// </summary>
        public static string Enter_your_email_and_password_to_sign_in {
            get {
                return ResourceManager.GetString("Enter your email and password to sign in", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First Name.
        /// </summary>
        public static string FirstName {
            get {
                return ResourceManager.GetString("FirstName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Floor Number.
        /// </summary>
        public static string FloorNo {
            get {
                return ResourceManager.GetString("FloorNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Floor Number.
        /// </summary>
        public static string FloorsNo {
            get {
                return ResourceManager.GetString("FloorsNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Forgot your password?.
        /// </summary>
        public static string Forgot_your_password_ {
            get {
                return ResourceManager.GetString("Forgot your password?", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to From.
        /// </summary>
        public static string From {
            get {
                return ResourceManager.GetString("From", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Full Address.
        /// </summary>
        public static string FullAddress {
            get {
                return ResourceManager.GetString("FullAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Full Adreess Arabic.
        /// </summary>
        public static string FullAddressAr {
            get {
                return ResourceManager.GetString("FullAddressAr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Full Address English .
        /// </summary>
        public static string FullAddressEn {
            get {
                return ResourceManager.GetString("FullAddressEn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Furniture and stores.
        /// </summary>
        public static string Furniture_and_stores {
            get {
                return ResourceManager.GetString("Furniture and stores", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to gps.
        /// </summary>
        public static string gps {
            get {
                return ResourceManager.GetString("gps", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Guest Name.
        /// </summary>
        public static string Guest_Name {
            get {
                return ResourceManager.GetString("Guest Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home.
        /// </summary>
        public static string Home {
            get {
                return ResourceManager.GetString("Home", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hospitality Contract ?.
        /// </summary>
        public static string Hospitality_Contract__ {
            get {
                return ResourceManager.GetString("Hospitality Contract ?", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hospitality Contracts Report.
        /// </summary>
        public static string HospitalityContractsReport {
            get {
                return ResourceManager.GetString("HospitalityContractsReport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hotel.
        /// </summary>
        public static string Hotel {
            get {
                return ResourceManager.GetString("Hotel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hotel Contact.
        /// </summary>
        public static string Hotel_Contact {
            get {
                return ResourceManager.GetString("Hotel Contact", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ID.
        /// </summary>
        public static string ID {
            get {
                return ResourceManager.GetString("ID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Id Type.
        /// </summary>
        public static string Id_Type {
            get {
                return ResourceManager.GetString("Id Type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to National ID.
        /// </summary>
        public static string IdValue {
            get {
                return ResourceManager.GetString("IdValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Initial quantity.
        /// </summary>
        public static string IntailQty {
            get {
                return ResourceManager.GetString("IntailQty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to invoice info..
        /// </summary>
        public static string invoice_info_ {
            get {
                return ResourceManager.GetString("invoice info.", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to invoice Taxes.
        /// </summary>
        public static string invoice_Taxes {
            get {
                return ResourceManager.GetString("invoice Taxes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Affiliated with the company ?.
        /// </summary>
        public static string IsCompony {
            get {
                return ResourceManager.GetString("IsCompony", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Is Fixed.
        /// </summary>
        public static string IsFixed {
            get {
                return ResourceManager.GetString("IsFixed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Registered in another hotel&apos;s data ?.
        /// </summary>
        public static string IsShare {
            get {
                return ResourceManager.GetString("IsShare", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ar-SA.
        /// </summary>
        public static string lan {
            get {
                return ResourceManager.GetString("lan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to last Name.
        /// </summary>
        public static string LastName {
            get {
                return ResourceManager.GetString("LastName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log in.
        /// </summary>
        public static string Log_in {
            get {
                return ResourceManager.GetString("Log in", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to log in Hotel.
        /// </summary>
        public static string log_in_Hotel {
            get {
                return ResourceManager.GetString("log in Hotel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login.
        /// </summary>
        public static string Login {
            get {
                return ResourceManager.GetString("Login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logo.
        /// </summary>
        public static string Logo {
            get {
                return ResourceManager.GetString("Logo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logout.
        /// </summary>
        public static string Logout {
            get {
                return ResourceManager.GetString("Logout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Min Price.
        /// </summary>
        public static string MinPrice {
            get {
                return ResourceManager.GetString("MinPrice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Min Price With Breakfast.
        /// </summary>
        public static string MinPriceWithBreakfast {
            get {
                return ResourceManager.GetString("MinPriceWithBreakfast", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Min Price With Dinner.
        /// </summary>
        public static string MinPriceWithDinner {
            get {
                return ResourceManager.GetString("MinPriceWithDinner", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Min Price With Lunch.
        /// </summary>
        public static string MinPriceWithLunch {
            get {
                return ResourceManager.GetString("MinPriceWithLunch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Arabic Name.
        /// </summary>
        public static string NameAr {
            get {
                return ResourceManager.GetString("NameAr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to English Name.
        /// </summary>
        public static string NameEn {
            get {
                return ResourceManager.GetString("NameEn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nationality.
        /// </summary>
        public static string Nationality {
            get {
                return ResourceManager.GetString("Nationality", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Assets/Products Report.
        /// </summary>
        public static string Naturel_of_Asset_Report {
            get {
                return ResourceManager.GetString("Naturel of Asset Report", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Naturel of Payment.
        /// </summary>
        public static string naturel_of_Payment {
            get {
                return ResourceManager.GetString("naturel of Payment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Assets/Products.
        /// </summary>
        public static string NaturelofAsset {
            get {
                return ResourceManager.GetString("NaturelofAsset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Naturel of Contract.
        /// </summary>
        public static string Naturelofcontract {
            get {
                return ResourceManager.GetString("Naturelofcontract", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Contract.
        /// </summary>
        public static string New_Contract {
            get {
                return ResourceManager.GetString("New Contract", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Payment Voucher.
        /// </summary>
        public static string New_Payment_Voucher {
            get {
                return ResourceManager.GetString("New Payment Voucher", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Recepit Voucher.
        /// </summary>
        public static string New_Receipt_Voucher {
            get {
                return ResourceManager.GetString("New Receipt Voucher", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Normal Price.
        /// </summary>
        public static string NormalPrice {
            get {
                return ResourceManager.GetString("NormalPrice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number of Clients.
        /// </summary>
        public static string Number_of_Clients {
            get {
                return ResourceManager.GetString("Number of Clients", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number of Employees.
        /// </summary>
        public static string Number_of_Employees {
            get {
                return ResourceManager.GetString("Number of Employees", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number of Rooms.
        /// </summary>
        public static string Number_of_Rooms {
            get {
                return ResourceManager.GetString("Number of Rooms", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Off Service Rooms.
        /// </summary>
        public static string Off_Service_Rooms {
            get {
                return ResourceManager.GetString("Off Service Rooms", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Operation.
        /// </summary>
        public static string Operation {
            get {
                return ResourceManager.GetString("Operation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        public static string Password {
            get {
                return ResourceManager.GetString("Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Payment Method.
        /// </summary>
        public static string Payment_Method {
            get {
                return ResourceManager.GetString("Payment Method", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Payment Date.
        /// </summary>
        public static string paymentDate {
            get {
                return ResourceManager.GetString("paymentDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Payment Type.
        /// </summary>
        public static string PaymentType {
            get {
                return ResourceManager.GetString("PaymentType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phone/Email/......
        /// </summary>
        public static string phone_Email {
            get {
                return ResourceManager.GetString("phone/Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Post Box.
        /// </summary>
        public static string PostBox {
            get {
                return ResourceManager.GetString("PostBox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Price.
        /// </summary>
        public static string Price {
            get {
                return ResourceManager.GetString("Price", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to price for one day.
        /// </summary>
        public static string price_for_one_day {
            get {
                return ResourceManager.GetString("price for one day", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Price With Breakfast.
        /// </summary>
        public static string PriceWithBreakfast {
            get {
                return ResourceManager.GetString("PriceWithBreakfast", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Price With Dinner.
        /// </summary>
        public static string PriceWithDinner {
            get {
                return ResourceManager.GetString("PriceWithDinner", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Price With Lunch.
        /// </summary>
        public static string PriceWithLunch {
            get {
                return ResourceManager.GetString("PriceWithLunch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Print Report.
        /// </summary>
        public static string Print_Report {
            get {
                return ResourceManager.GetString("Print Report", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Product.
        /// </summary>
        public static string Product {
            get {
                return ResourceManager.GetString("Product", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Products.
        /// </summary>
        public static string Products {
            get {
                return ResourceManager.GetString("Products", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Purchases invoice.
        /// </summary>
        public static string Purchases_invoice {
            get {
                return ResourceManager.GetString("Purchases invoice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Purpose Visit.
        /// </summary>
        public static string PurposeVisit {
            get {
                return ResourceManager.GetString("PurposeVisit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quantity.
        /// </summary>
        public static string Qty {
            get {
                return ResourceManager.GetString("Qty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reciept Date.
        /// </summary>
        public static string Reciept_Date {
            get {
                return ResourceManager.GetString("Reciept Date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reciept Vouchers Report.
        /// </summary>
        public static string Reciept_Vouchers_Report {
            get {
                return ResourceManager.GetString("Reciept Vouchers Report", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Register.
        /// </summary>
        public static string Register {
            get {
                return ResourceManager.GetString("Register", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Register as a new user.
        /// </summary>
        public static string Register_as_a_new_user {
            get {
                return ResourceManager.GetString("Register as a new user", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rent Contracts Reports.
        /// </summary>
        public static string Rent_Contracts_Reports {
            get {
                return ResourceManager.GetString("Rent Contracts Reports", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rent info..
        /// </summary>
        public static string Rent_info {
            get {
                return ResourceManager.GetString("Rent info", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reports.
        /// </summary>
        public static string Reports {
            get {
                return ResourceManager.GetString("Reports", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resend email confirmation.
        /// </summary>
        public static string Resend_email_confirmation {
            get {
                return ResourceManager.GetString("Resend email confirmation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reservation.
        /// </summary>
        public static string Reservation {
            get {
                return ResourceManager.GetString("Reservation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reserved Rooms.
        /// </summary>
        public static string Reserved_Rooms {
            get {
                return ResourceManager.GetString("Reserved Rooms", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Responsable Name.
        /// </summary>
        public static string ResponsableName {
            get {
                return ResourceManager.GetString("ResponsableName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Room.
        /// </summary>
        public static string Room {
            get {
                return ResourceManager.GetString("Room", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Room furniture.
        /// </summary>
        public static string Room_furniture {
            get {
                return ResourceManager.GetString("Room furniture", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Room info..
        /// </summary>
        public static string Room_info {
            get {
                return ResourceManager.GetString("Room info", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Room Price With Breakfast.
        /// </summary>
        public static string Room_Price_With_Breakfast {
            get {
                return ResourceManager.GetString("Room Price With Breakfast", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Room Price Without Breakfast.
        /// </summary>
        public static string Room_Price_Without_Breakfast {
            get {
                return ResourceManager.GetString("Room Price Without Breakfast", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Room Report.
        /// </summary>
        public static string Room_Report {
            get {
                return ResourceManager.GetString("Room Report", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Room Asset.
        /// </summary>
        public static string RoomAsset {
            get {
                return ResourceManager.GetString("RoomAsset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Room Number.
        /// </summary>
        public static string RoomNo {
            get {
                return ResourceManager.GetString("RoomNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rooms Report.
        /// </summary>
        public static string Rooms_Report {
            get {
                return ResourceManager.GetString("Rooms Report", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rooms.
        /// </summary>
        public static string Roomscheme {
            get {
                return ResourceManager.GetString("Roomscheme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Room Number.
        /// </summary>
        public static string RoomsNo {
            get {
                return ResourceManager.GetString("RoomsNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Room Status.
        /// </summary>
        public static string RoomStatus {
            get {
                return ResourceManager.GetString("RoomStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Room Type.
        /// </summary>
        public static string RoomType {
            get {
                return ResourceManager.GetString("RoomType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to search.
        /// </summary>
        public static string search {
            get {
                return ResourceManager.GetString("search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select.
        /// </summary>
        public static string select {
            get {
                return ResourceManager.GetString("select", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Serial Number.
        /// </summary>
        public static string SerialNo {
            get {
                return ResourceManager.GetString("SerialNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Service invoice.
        /// </summary>
        public static string Service_invoice {
            get {
                return ResourceManager.GetString("Service invoice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Services.
        /// </summary>
        public static string Services {
            get {
                return ResourceManager.GetString("Services", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        public static string Settings {
            get {
                return ResourceManager.GetString("Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Single Bed Number.
        /// </summary>
        public static string SingleBedNo {
            get {
                return ResourceManager.GetString("SingleBedNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start Date.
        /// </summary>
        public static string StartDate {
            get {
                return ResourceManager.GetString("StartDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Store.
        /// </summary>
        public static string Store {
            get {
                return ResourceManager.GetString("Store", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Store content.
        /// </summary>
        public static string Store_content {
            get {
                return ResourceManager.GetString("Store content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Store Responsables.
        /// </summary>
        public static string Store_Responsables {
            get {
                return ResourceManager.GetString("Store Responsables", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stores.
        /// </summary>
        public static string Stores {
            get {
                return ResourceManager.GetString("Stores", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Submit.
        /// </summary>
        public static string Submit {
            get {
                return ResourceManager.GetString("Submit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tax Type.
        /// </summary>
        public static string TaxType {
            get {
                return ResourceManager.GetString("TaxType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To.
        /// </summary>
        public static string To {
            get {
                return ResourceManager.GetString("To", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total.
        /// </summary>
        public static string Total {
            get {
                return ResourceManager.GetString("Total", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total Contract Value.
        /// </summary>
        public static string Total_Contract_Value {
            get {
                return ResourceManager.GetString("Total Contract Value", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total Cost.
        /// </summary>
        public static string Total_Cost {
            get {
                return ResourceManager.GetString("Total Cost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total Income.
        /// </summary>
        public static string Total_Income {
            get {
                return ResourceManager.GetString("Total Income", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total invoice Value.
        /// </summary>
        public static string Total_invoice_Value {
            get {
                return ResourceManager.GetString("Total invoice Value", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total Number.
        /// </summary>
        public static string Total_Number {
            get {
                return ResourceManager.GetString("Total Number", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total Number of Daily Contracts.
        /// </summary>
        public static string Total_Number_of_Daily_Contracts {
            get {
                return ResourceManager.GetString("Total Number of Daily Contracts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total Remaining Value.
        /// </summary>
        public static string Total_Remaining_Value {
            get {
                return ResourceManager.GetString("Total Remaining Value", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total Rooms Income.
        /// </summary>
        public static string Total_Rooms_Income {
            get {
                return ResourceManager.GetString("Total Rooms Income", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total Rooms Income Report.
        /// </summary>
        public static string Total_Rooms_Income_Report {
            get {
                return ResourceManager.GetString("Total Rooms Income Report", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total Value of Daily Contracts.
        /// </summary>
        public static string Total_Value_of_Daily_Contracts {
            get {
                return ResourceManager.GetString("Total Value of Daily Contracts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total value with taxes.
        /// </summary>
        public static string Total_value_with_taxes {
            get {
                return ResourceManager.GetString("Total value with taxes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total Price.
        /// </summary>
        public static string TotalPrice {
            get {
                return ResourceManager.GetString("TotalPrice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remaining Value.
        /// </summary>
        public static string TotalRemainingValue {
            get {
                return ResourceManager.GetString("TotalRemainingValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unit Type.
        /// </summary>
        public static string Unit_Type {
            get {
                return ResourceManager.GetString("Unit Type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unit Price.
        /// </summary>
        public static string unitPrice {
            get {
                return ResourceManager.GetString("unitPrice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unit Types.
        /// </summary>
        public static string UnitTypes {
            get {
                return ResourceManager.GetString("UnitTypes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value.
        /// </summary>
        public static string Value {
            get {
                return ResourceManager.GetString("Value", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vat Number.
        /// </summary>
        public static string VatNo {
            get {
                return ResourceManager.GetString("VatNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vendor Contact.
        /// </summary>
        public static string Vendor_Contact {
            get {
                return ResourceManager.GetString("Vendor Contact", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vendors.
        /// </summary>
        public static string Vendors {
            get {
                return ResourceManager.GetString("Vendors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wc Number.
        /// </summary>
        public static string WcNo {
            get {
                return ResourceManager.GetString("WcNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Welcome.
        /// </summary>
        public static string Welcome {
            get {
                return ResourceManager.GetString("Welcome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Welcome back.
        /// </summary>
        public static string Welcome_back {
            get {
                return ResourceManager.GetString("Welcome back", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zipe Code.
        /// </summary>
        public static string ZipeCode {
            get {
                return ResourceManager.GetString("ZipeCode", resourceCulture);
            }
        }
    }
}
